module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/tests/e2e'],
  testMatch: ['**/*.e2e.test.ts'],
  transform: {
    '^.+\\.ts$': 'ts-jest',
  },
  moduleNameMapper: {
    '^@/auth/(.*)$': '<rootDir>/src/modules/auth/$1',
    '^@/user/(.*)$': '<rootDir>/src/modules/user/$1',
    '^@/modules/(.*)$': '<rootDir>/src/modules/$1',
    '^@/shared/utils/(.*)$': '<rootDir>/src/shared/utils/$1',
    '^@/shared/middleware/(.*)$': '<rootDir>/src/shared/middleware/$1',
    '^@/shared/config/(.*)$': '<rootDir>/src/shared/config/$1',
    '^@/shared/database/(.*)$': '<rootDir>/src/shared/database/$1',
    '^@/shared/core/(.*)$': '<rootDir>/src/shared/core/$1',
    '^@/shared/types/(.*)$': '<rootDir>/src/shared/types/$1',
    '^@/shared/(.*)$': '<rootDir>/src/shared/$1',
    '^@/models/(.*)$': '<rootDir>/src/models/$1',
    '^@/(.*)$': '<rootDir>/src/$1',
  },
  setupFilesAfterEnv: ['<rootDir>/tests/e2e/setup.ts'],
  testTimeout: 30000,
  maxWorkers: 1,
}; 