module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src', '<rootDir>/tests'],
  testMatch: ['**/__tests__/**/*.ts', '**/?(*.)+(spec|test).ts'],
  transform: {
    '^.+\\.ts$': 'ts-jest',
  },
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.d.ts',
    '!src/index.ts',
    '!src/database/migrations/**',
    '!src/database/seeds/**',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  moduleNameMapper: {
    '^@/auth/(.*)$': '<rootDir>/src/modules/auth/$1',
    '^@/user/(.*)$': '<rootDir>/src/modules/user/$1',
    '^@/modules/(.*)$': '<rootDir>/src/modules/$1',
    '^@/shared/utils/(.*)$': '<rootDir>/src/shared/utils/$1',
    '^@/shared/middleware/(.*)$': '<rootDir>/src/shared/middleware/$1',
    '^@/shared/config/(.*)$': '<rootDir>/src/shared/config/$1',
    '^@/shared/database/(.*)$': '<rootDir>/src/shared/database/$1',
    '^@/shared/core/(.*)$': '<rootDir>/src/shared/core/$1',
    '^@/shared/types/(.*)$': '<rootDir>/src/shared/types/$1',
    '^@/shared/(.*)$': '<rootDir>/src/shared/$1',
    '^@/models/(.*)$': '<rootDir>/src/models/$1',
    '^@/(.*)$': '<rootDir>/src/$1',
  },
  setupFilesAfterEnv: ['<rootDir>/tests/setup.ts'],
  testTimeout: 10000,
}; 